version: "3"
services:
  terraform:
    container_name: "terraform"
    image: local/terraform-tips
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./terraform:/root/tf
