version: "3"
services:
  terraform:
    container_name: "terraform"
    image: local/terraform-samples-for-aws
    build:
      context: ./
      dockerfile: Dockerfile.al2023
    volumes:
      - ./terraform:/root/tf
      - ./tools:/root/tools
      - ~/.aws/:/root/.aws:ro   # aws credentials and others; read-only
    environment:
      # AWS_ACCESS_KEY_ID     : ${AWS_ACCESS_KEY_ID}
      # AWS_SECRET_ACCESS_KEY : ${AWS_SECRET_ACCESS_KEY}
      # AWS_DEFAULT_REGION    : ${AWS_DEFAULT_REGION}
      - AWS_SDK_LOAD_CONFIG
      - AWS_PROFILE
